Bring back push fallback on watch

diff --git a/joia b/joia
--- a/joia
+++ b/joia
@@ -143,6 +143,13 @@ joia_watch () {
     # Only run deploy on output from sync
     # (since files have been updated on the instance)
     sync_out="$(joia_sync 2>&1)"
+
+    # If sync errors (maybe due to lack of unison) try push
+    if [ $? -ne 0 ]; then
+      echo "Error running sync, falling back to push"
+      sync_out="$(joia_push 2>&1)"
+    fi
+
     if [ "$sync_out" ]; then
       echo "$sync_out"
       joia_deploy
